"""
Persistent document registry for OmniMind.

This module manages the lifecycle metadata of documents that are
registered with OmniMind.

The registry is persisted as JSON so document information survives
application restarts.

Important:
- A document is identified using the stable document_id generated by
  the document loader.
- Registering a document does NOT index it into Qdrant.
- Removing a document from the registry does NOT delete the original
  source file or vector data.
"""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from rag.ingestion.loader import load_pdf


class DocumentManager:
    """
    Persistent registry for OmniMind documents.

    Example:
        manager = DocumentManager()

        document = manager.add_document(
            "data/raw/sample.pdf"
        )

        print(document["document_id"])

        documents = manager.list_documents()
    """

    DEFAULT_REGISTRY_PATH = Path(
        "data/processed/document_registry.json"
    )

    VALID_STATUSES = {
        "registered",
        "processing",
        "indexed",
        "failed",
        "removed",
    }

    def __init__(
        self,
        registry_path: str | Path | None = None,
    ) -> None:
        """
        Initialize the document manager.

        Args:
            registry_path:
                Path to the persistent JSON registry.
                Defaults to:
                data/processed/document_registry.json
        """
        self.registry_path = Path(
            registry_path
            if registry_path is not None
            else self.DEFAULT_REGISTRY_PATH
        )

        self.registry_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        self._documents: dict[str, dict[str, Any]] = {}

        self._load_registry()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _utc_now() -> str:
        """
        Return the current UTC timestamp in ISO-8601 format.
        """
        return datetime.now(timezone.utc).isoformat()

    @staticmethod
    def _validate_pdf_path(
        file_path: str | Path,
    ) -> Path:
        """
        Validate and normalize a PDF path.
        """
        path = Path(file_path).expanduser().resolve()

        if not path.exists():
            raise FileNotFoundError(
                f"Document not found: {path}"
            )

        if not path.is_file():
            raise ValueError(
                f"Document path is not a file: {path}"
            )

        if path.suffix.lower() != ".pdf":
            raise ValueError(
                f"Only PDF documents are currently supported: {path}"
            )

        return path

    @staticmethod
    def _calculate_file_size(
        file_path: Path,
    ) -> int:
        """
        Return file size in bytes.
        """
        return file_path.stat().st_size

    def _load_registry(self) -> None:
        """
        Load the persistent registry from disk.

        If the registry does not exist, an empty registry is created
        in memory.
        """
        if not self.registry_path.exists():
            self._documents = {}
            return

        try:
            with self.registry_path.open(
                "r",
                encoding="utf-8",
            ) as file:
                data = json.load(file)

        except json.JSONDecodeError as exc:
            raise ValueError(
                f"Invalid document registry JSON: "
                f"{self.registry_path}"
            ) from exc

        if not isinstance(data, dict):
            raise ValueError(
                "Document registry must contain a JSON object."
            )

        documents = data.get("documents", {})

        if not isinstance(documents, dict):
            raise ValueError(
                "The 'documents' field must be a JSON object."
            )

        self._documents = documents

    def _save_registry(self) -> None:
        """
        Persist the registry atomically.

        A temporary file is written first and then replaced over the
        existing registry. This reduces the chance of leaving behind
        a partially written JSON file.
        """
        self.registry_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        registry_data = {
            "version": 1,
            "updated_at": self._utc_now(),
            "documents": self._documents,
        }

        fd, temp_path = tempfile.mkstemp(
            prefix=".document_registry_",
            suffix=".tmp",
            dir=str(self.registry_path.parent),
        )

        try:
            with os.fdopen(
                fd,
                "w",
                encoding="utf-8",
            ) as file:
                json.dump(
                    registry_data,
                    file,
                    indent=2,
                    ensure_ascii=False,
                )
                file.write("\n")

            os.replace(
                temp_path,
                self.registry_path,
            )

        except Exception:
            try:
                os.unlink(temp_path)
            except FileNotFoundError:
                pass

            raise

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_document(
        self,
        file_path: str | Path,
        *,
        allow_duplicate: bool = False,
    ) -> dict[str, Any]:
        """
        Register a PDF document.

        The document loader is used to obtain the stable document_id
        and document metadata.

        Args:
            file_path:
                Path to the PDF.

            allow_duplicate:
                If False, registering the same document again raises
                ValueError.

        Returns:
            The registered document metadata.
        """
        path = self._validate_pdf_path(file_path)

        # Load the PDF so that we use the same deterministic
        # document identity and metadata as the ingestion pipeline.
        pages = load_pdf(path)

        if not pages:
            raise ValueError(
                f"PDF contains no readable pages: {path}"
            )

        first_page_metadata = pages[0].get(
            "metadata",
            {},
        )

        if not isinstance(first_page_metadata, dict):
            first_page_metadata = {}

        document_id = first_page_metadata.get(
            "document_id"
        )

        if not document_id:
            raise ValueError(
                "PDF loader did not provide a document_id."
            )

        document_id = str(document_id)

        existing = self._documents.get(document_id)

        if existing is not None and not allow_duplicate:
            raise ValueError(
                f"Document is already registered: "
                f"{document_id}"
            )

        # Calculate page information.
        page_count = len(pages)

        text_page_count = 0

        for page in pages:
            text = page.get("text", "")

            if isinstance(text, str) and text.strip():
                text_page_count += 1

        now = self._utc_now()

        document = {
            "document_id": document_id,
            "document_name": path.name,
            "file_path": str(path),
            "source": first_page_metadata.get(
                "source",
                str(path),
            ),
            "source_type": first_page_metadata.get(
                "source_type",
                "pdf",
            ),
            "page_count": page_count,
            "text_page_count": text_page_count,
            "file_size_bytes": self._calculate_file_size(path),
            "status": "registered",
            "created_at": (
                existing.get("created_at", now)
                if existing
                else now
            ),
            "updated_at": now,
        }

        self._documents[document_id] = document

        self._save_registry()

        return document

    def get_document(
        self,
        document_id: str,
    ) -> dict[str, Any] | None:
        """
        Retrieve a document by document_id.

        Returns:
            Document metadata or None if not found.
        """
        document_id = str(document_id).strip()

        if not document_id:
            return None

        return self._documents.get(document_id)

    def get_document_by_path(
        self,
        file_path: str | Path,
    ) -> dict[str, Any] | None:
        """
        Retrieve a registered document using its file path.

        Path comparison is normalized to an absolute resolved path.
        """
        path = Path(file_path).expanduser().resolve()

        target_path = str(path)

        for document in self._documents.values():
            registered_path = document.get("file_path")

            if registered_path is None:
                continue

            try:
                normalized_registered_path = str(
                    Path(registered_path)
                    .expanduser()
                    .resolve()
                )
            except (OSError, RuntimeError):
                normalized_registered_path = str(
                    registered_path
                )

            if normalized_registered_path == target_path:
                return document

        return None

    def list_documents(
        self,
        status: str | None = None,
    ) -> list[dict[str, Any]]:
        """
        Return registered documents.

        Args:
            status:
                Optional status filter.

        Returns:
            List of document metadata dictionaries.
        """
        if status is not None:
            status = str(status).strip()

            if status not in self.VALID_STATUSES:
                raise ValueError(
                    f"Invalid document status: {status}"
                )

        documents = list(self._documents.values())

        if status is not None:
            documents = [
                document
                for document in documents
                if document.get("status") == status
            ]

        # Stable ordering makes tests and API responses deterministic.
        documents.sort(
            key=lambda item: (
                item.get("document_name", ""),
                item.get("document_id", ""),
            )
        )

        return documents

    def count(
        self,
        status: str | None = None,
    ) -> int:
        """
        Return the number of registered documents.

        Args:
            status:
                Optional status filter.
        """
        if status is None:
            return len(self._documents)

        return len(
            self.list_documents(status=status)
        )

    def update_status(
        self,
        document_id: str,
        status: str,
    ) -> dict[str, Any]:
        """
        Update the processing status of a document.

        Returns:
            Updated document metadata.

        Raises:
            KeyError:
                If the document does not exist.

            ValueError:
                If the status is invalid.
        """
        document_id = str(document_id).strip()
        status = str(status).strip()

        if not document_id:
            raise ValueError(
                "document_id cannot be empty."
            )

        if status not in self.VALID_STATUSES:
            raise ValueError(
                f"Invalid document status: {status}"
            )

        if document_id not in self._documents:
            raise KeyError(
                f"Document not found: {document_id}"
            )

        self._documents[document_id]["status"] = status
        self._documents[document_id][
            "updated_at"
        ] = self._utc_now()

        self._save_registry()

        return self._documents[document_id]

    def remove_document(
        self,
        document_id: str,
    ) -> bool:
        """
        Remove a document from the persistent registry.

        IMPORTANT:
            This method only removes the registry entry.

            It does NOT:
            - delete the original PDF
            - delete processed files
            - delete Qdrant vectors
            - remove other application data

        Args:
            document_id:
                Stable document identifier.

        Returns:
            True if the document existed and was removed.
            False if the document was not found.
        """
        document_id = str(document_id).strip()

        if not document_id:
            return False

        if document_id not in self._documents:
            return False

        del self._documents[document_id]

        self._save_registry()

        return True

    def get_registry_info(self) -> dict[str, Any]:
        """
        Return registry-level information.
        """
        documents = self.list_documents()

        status_counts: dict[str, int] = {}

        for document in documents:
            status = document.get(
                "status",
                "unknown",
            )

            status_counts[status] = (
                status_counts.get(status, 0) + 1
            )

        return {
            "registry_path": str(
                self.registry_path.resolve()
            ),
            "document_count": len(documents),
            "status_counts": status_counts,
            "documents": documents,
        }