"""
Multi-query retrieval for OmniMind.

Runs hybrid retrieval over multiple query variations generated by
QueryExpander and combines the results using Reciprocal Rank Fusion (RRF).

This module is deterministic and does not require an LLM.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from rag.retrieval.query_expansion import QueryExpander


class MultiQueryRetriever:
    """
    Retrieve documents using multiple query variations.

    Each expanded query is sent to the supplied hybrid retriever.
    Results are fused using Reciprocal Rank Fusion.
    """

    def __init__(
        self,
        hybrid_retriever: Any,
        query_expander: Optional[QueryExpander] = None,
        rrf_k: int = 60,
        max_queries: int = 3,
    ):
        if rrf_k <= 0:
            raise ValueError("rrf_k must be greater than 0")

        if max_queries <= 0:
            raise ValueError("max_queries must be greater than 0")

        self.hybrid_retriever = hybrid_retriever
        self.query_expander = query_expander or QueryExpander(
            max_queries=max_queries
        )
        self.rrf_k = rrf_k
        self.max_queries = max_queries

    @staticmethod
    def _result_id(result: Dict[str, Any]) -> str:
        """
        Extract a stable identifier from a retrieval result.
        """

        result_id = result.get("result_id")

        if result_id:
            return str(result_id)

        metadata = result.get("metadata") or {}

        for key in ("chunk_id", "id", "document_id"):
            value = metadata.get(key)

            if value:
                return str(value)

        text = result.get("text", "")

        return f"text:{hash(text)}"

    @staticmethod
    def _copy_result(result: Dict[str, Any]) -> Dict[str, Any]:
        """
        Copy a result so the original hybrid retriever output is not mutated.
        """

        copied = dict(result)

        metadata = copied.get("metadata")

        if isinstance(metadata, dict):
            copied["metadata"] = dict(metadata)

        return copied

    def retrieve(
        self,
        query: str,
        top_k: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve and fuse results from multiple query variations.

        Parameters
        ----------
        query:
            Original user query.

        top_k:
            Number of final fused results.

        Returns
        -------
        List[Dict[str, Any]]
            Ranked multi-query retrieval results.
        """

        if top_k <= 0:
            return []

        expanded_queries = self.query_expander.expand(query)

        if not expanded_queries:
            return []

        fused: Dict[str, Dict[str, Any]] = {}

        for query_index, expanded_query in enumerate(
            expanded_queries[: self.max_queries],
            start=1,
        ):
            results = self.hybrid_retriever.retrieve(
                expanded_query,
                top_k=top_k,
            )

            for rank, result in enumerate(results, start=1):
                if not isinstance(result, dict):
                    continue

                result_id = self._result_id(result)

                if result_id not in fused:
                    fused[result_id] = self._copy_result(result)

                    fused[result_id]["multi_query_score"] = 0.0
                    fused[result_id]["multi_query_rank"] = 0
                    fused[result_id]["multi_query_sources"] = []
                    fused[result_id]["multi_query_matches"] = 0

                item = fused[result_id]

                # Reciprocal Rank Fusion contribution.
                rrf_score = 1.0 / (self.rrf_k + rank)

                item["multi_query_score"] += rrf_score
                item["multi_query_matches"] += 1

                item["multi_query_sources"].append(
                    {
                        "query": expanded_query,
                        "query_index": query_index,
                        "rank": rank,
                        "rrf_score": rrf_score,
                    }
                )

        # Highest fused score first.
        ranked = sorted(
            fused.values(),
            key=lambda item: (
                item["multi_query_score"],
                item["multi_query_matches"],
            ),
            reverse=True,
        )

        ranked = ranked[:top_k]

        for final_rank, result in enumerate(ranked, start=1):
            result["multi_query_rank"] = final_rank

        return ranked


def multi_query_retrieve(
    hybrid_retriever: Any,
    query: str,
    top_k: int = 5,
    max_queries: int = 3,
    rrf_k: int = 60,
) -> List[Dict[str, Any]]:
    """
    Convenience function for multi-query retrieval.
    """

    retriever = MultiQueryRetriever(
        hybrid_retriever=hybrid_retriever,
        query_expander=QueryExpander(max_queries=max_queries),
        rrf_k=rrf_k,
        max_queries=max_queries,
    )

    return retriever.retrieve(
        query=query,
        top_k=top_k,
    )