from __future__ import annotations

from pathlib import Path
import sys
from typing import Any

# ============================================================
# PROJECT ROOT
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ============================================================
# IMPORTS
# ============================================================

from mcp.server import MCPServer

from rag.ingestion.document_manager import DocumentManager
from rag.retrieval.vector_store import QdrantVectorStore
from rag.retrieval.citations import build_citation


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_TOP_K = 5
MAX_TOP_K = 10

COLLECTION_NAME = "omnimind_documents"
QDRANT_URL = "http://127.0.0.1:6333"


# ============================================================
# PERSISTENT DOCUMENT KNOWLEDGE BASE
# ============================================================

class PersistentDocumentKnowledgeBase:
    """
    Persistent multi-document knowledge base backed by
    Qdrant Server.

    The MCP server intentionally does NOT load any embedding
    or reranker models.

    Architecture:

        Query Embedding
              |
              | generated by main OmniMind process
              v
        MCP Document Server
              |
              v
        Qdrant Server
              |
              v
        Citation Construction

    Keeping model inference outside the MCP subprocess avoids
    loading duplicate SentenceTransformer models and reduces
    memory usage.
    """

    def __init__(
        self,
        *,
        registry_path: str | Path | None = None,
        collection_name: str = COLLECTION_NAME,
        qdrant_url: str = QDRANT_URL,
    ) -> None:

        self.document_manager = DocumentManager(
            registry_path=registry_path,
        )

        self.vector_store = QdrantVectorStore(
            collection_name=collection_name,
            url=qdrant_url,
        )

    # ========================================================
    # VALIDATION
    # ========================================================

    @staticmethod
    def _validate_query_embedding(
        query_embedding: list[float],
    ) -> list[float]:

        if not isinstance(query_embedding, list):
            raise TypeError(
                "query_embedding must be a list."
            )

        if not query_embedding:
            raise ValueError(
                "query_embedding cannot be empty."
            )

        return query_embedding

    @staticmethod
    def _validate_top_k(
        top_k: int,
    ) -> int:

        if not isinstance(top_k, int):
            raise TypeError(
                "top_k must be an integer."
            )

        if top_k < 1 or top_k > MAX_TOP_K:
            raise ValueError(
                f"top_k must be between 1 and {MAX_TOP_K}."
            )

        return top_k

    def _validate_document_id(
        self,
        document_id: str | None,
    ) -> str | None:

        if document_id is None:
            return None

        document_id = str(document_id).strip()

        if not document_id:
            raise ValueError(
                "document_id cannot be empty."
            )

        document = self.document_manager.get_document(
            document_id
        )

        if document is None:
            raise ValueError(
                f"Document not found: {document_id}"
            )

        if document.get("status") != "indexed":
            raise ValueError(
                f"Document is not indexed: {document_id}"
            )

        if not self.vector_store.document_exists(
            document_id
        ):
            raise ValueError(
                f"Document has no indexed vectors: "
                f"{document_id}"
            )

        return document_id

    # ========================================================
    # SEARCH
    # ========================================================

    def search(
        self,
        query_embedding: list[float],
        *,
        top_k: int = DEFAULT_TOP_K,
        document_id: str | None = None,
        query: str = "",
    ) -> list[dict[str, Any]]:

        query_embedding = self._validate_query_embedding(
            query_embedding
        )

        top_k = self._validate_top_k(top_k)

        document_id = self._validate_document_id(
            document_id
        )

        # ----------------------------------------------------
        # Semantic retrieval from persistent Qdrant
        # ----------------------------------------------------

        candidates = self.vector_store.search(
            query_embedding=query_embedding,
            top_k=top_k,
            document_id=document_id,
        )

        if not candidates:
            return []

        # ----------------------------------------------------
        # Structured citations
        # ----------------------------------------------------

        output: list[dict[str, Any]] = []

        for rank, result in enumerate(
            candidates,
            start=1,
        ):

            item = dict(result)

            item["rank"] = rank

            metadata = dict(
                item.get("metadata", {})
            )

            item["document_id"] = (
                item.get("document_id")
                or metadata.get("document_id")
            )

            item["chunk_id"] = (
                item.get("chunk_id")
                or metadata.get("chunk_id")
            )

            item["document_name"] = (
                item.get("document_name")
                or metadata.get("document_name")
            )

            item["page"] = (
                item.get("page")
                or metadata.get("page")
            )

            item["citation"] = build_citation(
                item,
                rank,
            )

            output.append(item)

        return output

    # ========================================================
    # DOCUMENT INFO
    # ========================================================

    def get_document_info(
        self,
        document_id: str | None = None,
    ) -> dict[str, Any]:

        if document_id is None:

            return {
                "collection_name": COLLECTION_NAME,
                "qdrant_url": QDRANT_URL,
                "document_count": (
                    self.document_manager.count()
                ),
                "vector_count": (
                    self.vector_store.count()
                ),
            }

        document = self.document_manager.get_document(
            document_id
        )

        if document is None:

            return {
                "document_id": document_id,
                "found": False,
            }

        return {
            "document_id": document_id,
            "found": True,
            "document": document,
            "vector_count": (
                self.vector_store.count(
                    document_id=document_id
                )
            ),
        }

    # ========================================================
    # LIST DOCUMENTS
    # ========================================================

    def list_documents(
        self,
        status: str | None = None,
    ) -> list[dict[str, Any]]:

        return self.document_manager.list_documents(
            status=status
        )

    # ========================================================
    # CLOSE
    # ========================================================

    def close(self) -> None:

        self.vector_store.close()


# ============================================================
# GLOBAL KNOWLEDGE BASE
# ============================================================

_KNOWLEDGE_BASE: (
    PersistentDocumentKnowledgeBase | None
) = None


def get_knowledge_base() -> PersistentDocumentKnowledgeBase:

    global _KNOWLEDGE_BASE

    if _KNOWLEDGE_BASE is None:

        _KNOWLEDGE_BASE = (
            PersistentDocumentKnowledgeBase()
        )

    return _KNOWLEDGE_BASE


# ============================================================
# MCP SERVER
# ============================================================

server = MCPServer(
    name="omnimind-document-server"
)


# ============================================================
# MCP TOOLS
# ============================================================

@server.tool()
def search_documents(
    query_embedding: list[float],
    query: str = "",
    top_k: int = DEFAULT_TOP_K,
    document_id: str | None = None,
) -> dict[str, Any]:

    try:

        results = get_knowledge_base().search(
            query_embedding=query_embedding,
            query=query,
            top_k=top_k,
            document_id=document_id,
        )

        return {
            "query": query,
            "top_k": top_k,
            "document_id": document_id,
            "count": len(results),
            "results": results,
        }

    except Exception as exc:

        return {
            "query": query,
            "top_k": top_k,
            "document_id": document_id,
            "count": 0,
            "results": [],
            "error": str(exc),
        }


@server.tool()
def get_document_info(
    document_id: str | None = None,
) -> dict[str, Any]:

    try:

        return get_knowledge_base().get_document_info(
            document_id=document_id
        )

    except Exception as exc:

        return {
            "document_id": document_id,
            "error": str(exc),
        }


@server.tool()
def list_documents(
    status: str | None = None,
) -> dict[str, Any]:

    try:

        documents = (
            get_knowledge_base().list_documents(
                status=status
            )
        )

        return {
            "count": len(documents),
            "documents": documents,
        }

    except Exception as exc:

        return {
            "count": 0,
            "documents": [],
            "error": str(exc),
        }


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    try:

        server.run()

    except KeyboardInterrupt:

        pass

    finally:

        if _KNOWLEDGE_BASE is not None:

            _KNOWLEDGE_BASE.close()